name: "Map inputs"
description: "Maps workflow inputs to usable matrix arrays"
inputs:
  android:
    required: false
    default: "false"
    description: "If the android platform should be built"
  ios:
    required: false
    default: "false"
    description: "If the iOS platform should be built"
  test:
    required: false
    default: "false"
    description: "If a test build should be distributed"
  release:
    required: false
    default: "false"
    description: "If a production release should be published"
outputs:
  platforms:
    description: "Which platform to use to call fastlane lanes [ios, android]"
  types:
    description: 'Release type, [{ type: "test", lane: "firebase_distribution_release_all" }, { type: "release", lane: "store_release" }]'
runs:
  using: "node20"
  main: "index.js"
